### ISSUE TITLE
Support servers with plain http authentication 

### ISSUE THREAD

**Issue by guysoft** [photoprism/photoprism-mobile#34]
Hey, jwilder/nginx-proxy to get plain HTTP auth. And I need the app to support that.

This is also listed as a limitation in the README

**Comment by spaibs** [comment]
Yes, that's something we want to do, but the unsupported authentication in the README was related to PhotoPrism's own internal password protection.

In order to implement plain http auth in the mobile app, following steps need to be done:

- [ ] Move all remaining http calls to api.dart
- [ ] Write api wrapper which supports basic http auth: https://pub.dev/packages/http_auth
- [x] Add GUI in order to activate basic auth and insert username and password
- [x] Save user credentials in secure place, e.g. https://pub.dev/packages/flutter_secure_storage
- [ ] Search for uploader package which supports authentication

**Comment by guysoft** [comment]
I implemented https auth in a simpler way. I used jwilder/nginx-proxy. [explained here](https://github.com/jwilder/nginx-proxy#basic-authentication-support).
Also gives me https.

**Comment by spaibs** [comment]
You implemented authentication on the server, right? I have described the necessary steps that we have to program in the mobile app to implement basic auth.

**Comment by guysoft** [comment]
@spaibs Ah ok, didn't understand that

**Comment by thielepaul** [comment]
I agree that the app should support this and will have a look at it later today

**Comment by thielepaul** [comment]
@guysoft can you please check if [the newest apk](https://github.com/photoprism/photoprism-mobile/releases/download/latest/photoprism.apk) works for you?

**Comment by thielepaul** [comment]
> @guysoft can you please check if [this apk](https://github.com/photoprism/photoprism-mobile/suites/414454347/artifacts/1275577) works for you?

also feel free to reopen the issue if it is not working for you

**Comment by guysoft** [comment]
@thielepaul Yes that works!
